import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    default: "src/domains/default/index.tsx",
    tv: "src/domains/tv/index.tsx",
    conference: "src/domains/conference/index.tsx",
    festival: "src/domains/festival/index.tsx",
    healthcare: "src/domains/healthcare/index.tsx",
    gantt: "src/domains/gantt/index.tsx",
    venue: "src/domains/venue/index.tsx",
  },
  format: ["cjs", "esm"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  external: [
    "react",
    "react-dom",
    "lucide-react",
    "tailwindcss",
    "@radix-ui/react-popover",
    "@radix-ui/react-tabs",
    "@radix-ui/react-toggle-group",
    "@radix-ui/react-checkbox",
    "@radix-ui/react-slot",
    "react-day-picker",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "html2canvas",
    "jspdf",
  ],
  treeshake: true,
  minify: false,
})
